### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by 0xPugal** [devanshbatham/ParamSpider#112]
``paramspider -l domains.txt -s``
```
--SNIP--
[INFO] Fetching URLs for charts.redacted.com/
[INFO] Found 2 URLs for charts.redacted.com/
[INFO] Cleaning URLs for charts.redacted.com/
[INFO] Found 1 URLs after cleaning
[INFO] Extracting URLs with parameters
Traceback (most recent call last):
  File "/usr/local/bin/paramspider", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/paramspider/main.py", line 165, in main
    fetch_and_clean_urls(domain, extensions, args.stream,args.proxy, args.placeholder)
  File "/usr/local/lib/python3.10/dist-packages/paramspider/main.py", line 111, in fetch_and_clean_urls
    with open(result_file, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/charts.redacted.com/.txt'
```

**Comment by Ahmadzdddd** [comment]
I have similar error ! looks the  project is ending no one is responding!

**Comment by szybnev** [comment]
I have similar error. 

```python
Traceback (most recent call last):
  File "/home/redacted/tools/paramspider/venv/bin/paramspider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/redacted/tools/paramspider/venv/lib/python3.11/site-packages/paramspider/main.py", line 161, in main
    fetch_and_clean_urls(domain, extensions, args.stream, args.proxy, args.placeholder)
  File "/home/redacted/tools/paramspider/venv/lib/python3.11/site-packages/paramspider/main.py", line 111, in fetch_and_clean_urls
    with open(result_file, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'results/https://redacted.tld/services.php.txt'
```

OS specs:
```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2023.4"
VERSION="2023.4"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```

**Comment by devanshbatham** [comment]
`domains.txt` should be host names and not URLs. 

example.com ✅ 
https://example.com ❌ 
https://example.com/ ❌
