### ISSUE TITLE
paramspider is not working :(

### ISSUE THREAD

**Issue by shafiktanbir** [devanshbatham/ParamSpider#113]
$paramspider -d https://thecrownofficial.com/en/
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (5.2.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

           
                                      _    __       
   ___  ___ ________ ___ _  ___ ___  (_)__/ /__ ____
  / _ \/ _ `/ __/ _ `/  ' \(_-</ _ \/ / _  / -_) __/
 / .__/\_,_/_/  \_,_/_/_/_/___/ .__/_/\_,_/\__/_/   
/_/                          /_/                    

                              with <3 by @0xasm0d3us           
    
[INFO] Fetching URLs for https://thecrownofficial.com/en/
[INFO] Found 114 URLs for https://thecrownofficial.com/en/
[INFO] Cleaning URLs for https://thecrownofficial.com/en/
[INFO] Found 114 URLs after cleaning
[INFO] Extracting URLs with parameters
Traceback (most recent call last):
  File "/home/shafikul/.local/bin/paramspider", line 8, in <module>
    sys.exit(main())
  File "/home/shafikul/.local/lib/python3.9/site-packages/paramspider/main.py", line 161, in main
    fetch_and_clean_urls(domain, extensions, args.stream, args.proxy, args.placeholder)
  File "/home/shafikul/.local/lib/python3.9/site-packages/paramspider/main.py", line 111, in fetch_and_clean_urls
    with open(result_file, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/https://thecrownofficial.com/en/.txt'

i google it i haven't fine any soluation

**Comment by MinhPham123456789** [comment]
You should try remove the "https://" part in the domain name, that could be the problem because the script cannot create a directory name with "https://" in it (special character issue).

**Comment by ghost** [comment]
the problem is not http or https 
it is /en/ because linux dont create file name with slaces.
the author have to update his tool to check for this case as well
i will do it in future in my tool
https://github.com/knrredhelmet/paraminer
