### ISSUE TITLE
9

### ISSUE THREAD

**Issue by sasholy** [devanshbatham/ParamSpider#116]

**Comment by akhavanmohsen** [comment]
Hi,
I have also Traceback issue.

```
[INFO] Fetching URLs for https://kali.org
[INFO] Found 9351 URLs for https://kali.org
[INFO] Cleaning URLs for https://kali.org
[INFO] Found 3232 URLs after cleaning
[INFO] Extracting URLs with parameters
Traceback (most recent call last):
  File "/usr/local/bin/paramspider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/moh/.local/lib/python3.11/site-packages/paramspider/main.py", line 161, in main
    fetch_and_clean_urls(domain, extensions, args.stream, args.proxy, args.placeholder)
  File "/home/moh/.local/lib/python3.11/site-packages/paramspider/main.py", line 111, in fetch_and_clean_urls
    with open(result_file, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'results/https://kali.org.txt'

```

**Comment by NotoriousRebel** [comment]
@sasholy Your error is due to using python2.7, you are getting invalid syntax on `logging.info(f"{Fore.YELLOW}[INFO]{Style.RESET_ALL} Fetching URLs for {Fore.CYAN + domain + Style.RESET_ALL}")` because format strings (f"{}") were added in python3.6+. Use a version of python equal to or higher than 3.6

**Comment by 123yash8** [comment]
Install it with pip3 install .

**Comment by Anas-jaf** [comment]
don't use python2.7 pip version use pip3 python3.6+ version , that is your problem
