### ISSUE TITLE
Error execution pip install 

### ISSUE THREAD

**Issue by tXambe** [devanshbatham/ParamSpider#124]
Hello,

when I run pip install I have the next error:

`
pip install .                                                                                 
Defaulting to user installation because normal site-packages is not writeable
WARNING: Skipping /usr/local/lib/python3.11/dist-packages/contextvars-2.4.dist-info due to invalid metadata entry 'name'                                                                            
WARNING: Skipping /usr/local/lib/python3.11/dist-packages/immutables-0.20.dist-info due to invalid metadata entry 'name'                                                                            
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/knockpy-7.0.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330          
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/knockpy-5.4.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330          
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/tqdm-4.66.4-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330            
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/ipaddress-1.0.23-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330       
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/colorclass-2.2.2-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330       
WARNING: Skipping /usr/local/lib/python3.11/dist-packages/ipaddress-1.0.23-py3.11.egg/EGG-INFO due to invalid metadata entry 'name'                                                                 
WARNING: Skipping /usr/local/lib/python3.11/dist-packages/colorclass-2.2.2-py3.11.egg/EGG-INFO due to invalid metadata entry 'name'                                                                 
WARNING: Skipping /usr/local/lib/python3.11/dist-packages/contextvars-2.4.dist-info due to invalid metadata entry 'name'                                                                            
WARNING: Skipping /usr/local/lib/python3.11/dist-packages/immutables-0.20.dist-info due to invalid metadata entry 'name'                                                                            
WARNING: Skipping /usr/local/lib/python3.11/dist-packages/ipaddress-1.0.23-py3.11.egg/EGG-INFO due to invalid metadata entry 'name'                                                                 
WARNING: Skipping /usr/local/lib/python3.11/dist-packages/colorclass-2.2.2-py3.11.egg/EGG-INFO due to invalid metadata entry 'name'                                                                 
Processing /opt/WEB/IDENT-PARAMETERS/ParamSpider                                            
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/opt/PNTST/WEB/IDENT-PARAMETERS/ParamSpider/setup.py", line 3, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 74, in _install_setup_requires
          dist = MinimalDistribution(attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 56, in __init__
          super().__init__(filtered)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 483, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1041, in entry_points
          return SelectableGroups.load(eps).select(**params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 476, in load
          ordered = sorted(eps, key=by_group)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1038, in <genexpr>
          eps = itertools.chain.from_iterable(
                                             ^
        File "/usr/lib/python3.11/importlib/metadata/_itertools.py", line 16, in unique_everseen
          k = key(element)
              ^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 955, in _normalized_name
          or super()._normalized_name
             ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 627, in _normalized_name
          return Prepared.normalize(self.name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 882, in normalize
          return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
          return _compile(pattern, flags).sub(repl, string, count)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: expected string or bytes-like object, got 'NoneType'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

`

My version of pip is  24.0 and python 3.11

Anyone can help me ?

A greeting and thanks.

**Comment by rainman456** [comment]
use sudo pip3

**Comment by tXambe** [comment]
Hello,

same error

**Comment by ghost** [comment]
or use my tool
https://github.com/knrredhelmet/paraminer

**Comment by code6yte** [comment]
> or use my tool https://github.com/knrredhelmet/paraminer

Can anyone share this tool  bcz profile is deleted
