### ISSUE TITLE
file creation issue after running paramspider -l list.txt

### ISSUE THREAD

**Issue by rohandeb2** [devanshbatham/ParamSpider#133]
Traceback (most recent call last):
  File "/usr/local/bin/paramspider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/paramspider/main.py", line 165, in main
    fetch_and_clean_urls(domain, extensions, args.stream,args.proxy, args.placeholder)
  File "/usr/local/lib/python3.11/dist-packages/paramspider/main.py", line 111, in fetch_and_clean_urls
    with open(result_file, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'results/target.com/.txt'

**Comment by ghost** [comment]
i solved most of the error here
https://github.com/knrredhelmet/paraminer

**Comment by Moon-Launch** [comment]
https://github.com/knrredhelmet/paraminer gives 404 not found
