### ISSUE TITLE
TypeError: argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by changtraisitinh** [devanshbatham/ParamSpider#4]
```
    
Can not get target information
If you think this is a bug or unintentional behaviour. Report here : https://github.com/devanshbatham/ParamSpider/issues
Traceback (most recent call last):
  File "paramspider.py", line 73, in <module>
    main()
  File "paramspider.py", line 37, in main
    response = unquote(response)
  File "/usr/lib/python3.7/urllib/parse.py", line 609, in unquote
    if '%' not in string:
TypeError: argument of type 'bool' is not iterable

```

**Comment by devanshbatham** [comment]
Use python 3.7 +

**Comment by devanshbatham** [comment]
If still that does not solve your problem DM me here : Twitter/0xAsm0d3us , the problem is from your end , still I will try my best to get it resolved !
