### ISSUE TITLE
error!!  ##Traceback

### ISSUE THREAD

**Issue by cehbikramrock** [devanshbatham/ParamSpider#40]
Traceback (most recent call last):
  File "paramspider.py", line 1, in <module>
    from core import requester
  File "/home/user/Downloads/ParamSpider/core/requester.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
how to fix this bug can you please help me out

**Comment by devanshbatham** [comment]
Install the `requests` module !!
