### ISSUE TITLE
Error execution "No module named 'idna"

### ISSUE THREAD

**Issue by tXambe** [devanshbatham/ParamSpider#71]
Hello,

when I run paramspider I have this error.

```
Traceback (most recent call last):
  File "/opt/SPIDER/ParamSpider/paramspider.py", line 2, in <module>
    from core import requester
  File "/opt/SPIDER/ParamSpider/core/requester.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/usr/lib/python3/dist-packages/requests/packages.py", line 16, in <module>
    locals()[package] = __import__(package)
                        ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'idna'

```

I have installed idna but I don`t know because fail, anyone can help me?

A greeting and thanks

**Comment by devanshbatham** [comment]
Closing this issue as I have revamped this whole project. Check it out.

**Comment by tXambe** [comment]
Ok, thanks
